### ISSUE TITLE
repair coverage tool after migration on jest

### ISSUE THREAD

**Issue by dlukanin** [dlukanin/node-raspistill#15]

**Comment by georgettica** [comment]
Can I help?

**Comment by georgettica** [comment]
Can I help?

I have a PR waiting for approval and I needed to do the following:
install jest `npm install --save-dev jest`

also while running the test command I found that jest shows and error about Buffer, to fix it go through [this manual](https://nodejs.org/fr/docs/guides/buffer-constructor-deprecation/)

**Comment by dlukanin** [comment]
Hey. Thank you. But i think, your pr is not related to the current issue. Issue is about submitting coverage data to the coveralls.io - it is broken after migration on jest.

**Comment by flowwishthebest** [comment]
Hey, i will take it!
