### ISSUE TITLE
migrate to eslint

### ISSUE THREAD

**Issue by dlukanin** [dlukanin/node-raspistill#25]

**Comment by RedHoodJT1988** [comment]
I would like to help out with this. What is needed?

**Comment by aneeshrelan** [comment]
I am willing to help here too? Should any new error reported by eslint be fixed as part of this, or such rules are to be disabled?

**Comment by dlukanin** [comment]
@RedHoodJT1988 @aneeshrelan 
Hey! Thx for feedback. It will be good if tslint will migrate to eslint with same rules (if it is possible), and no new errors. I'll check new rules and enable them after this pr.
