### ISSUE TITLE
short interval time error

### ISSUE THREAD

**Issue by BenRoe** [dlukanin/node-raspistill#3]
Hello,
if i set a short interval time i get this error.
```
Raspistill Error: [Error: mmal: mmal_vc_component_enable: failed to enable component: ENOSPC
mmal: camera component couldn't be enabled
mmal: main: Failed to create camera component
mmal: Failed to run camera app. Please check for firmware updates
```

I use the `noFileSave ` option an save the file via fs.

**Comment by dlukanin** [comment]
Hello. Yes,  you will get error without camera timelapse mode because of big camera startup and taking photo time (the camera can't take several photos at the same time). I m implementing timelapse mode now and i think i will release new version of module with it in a few days.

**Comment by BenRoe** [comment]
@dlukanin that would be awesome.
I use your module to take picture with a pi zero and a gps module.

**Comment by dlukanin** [comment]
@BenRoe you can check out implemented timelapse mode, i've published new module version to npm.
