### ISSUE TITLE
timelaps unlimited time until condition is true

### ISSUE THREAD

**Issue by BenRoe** [dlukanin/node-raspistill#5]
Hi,
thank you for adding the time lapse feature.
Is there a way to take pictures unlimited time and until if a condition is true (if or button pressed) stop the time laps.

**Comment by dlukanin** [comment]
Hello.

According to docs (https://www.raspberrypi.org/documentation/raspbian/applications/camera.md) you can pass execTime = 0 to the timelapse method to run forever.

Cancelling running timelapse mode feature is good idea, in current module version in doesn't exist. I'll think about it.

**Comment by BenRoe** [comment]
`raspistill.stop( )` should work good. 
You can check the [node-raspicam](https://github.com/troyth/node-raspicam#raspicamstop-) module.

**Comment by dlukanin** [comment]
Thx, i'll check it out

**Comment by dlukanin** [comment]
Hello, you can check out new module version with implemented stop method.
